### ISSUE TITLE
Change the arrow icon above the text

### ISSUE THREAD

**Issue by CallumCoombes** [Shashank02051997/FancyWalkthrough-Android#1]
Is there a way to change the arrow icon above the text to a different icon? 

After testing a lot of users are mistaking it for an actual next button, whereas it is simply an image.

**Comment by ryust** [comment]
No response after all this time? Looks like another library that isn't maintained.

**Comment by Shashank02051997** [comment]
@CallumCoombes @ryust sorry for the late reply. New version is available in that i given the priority to hide the fab
